[package]
name = "skeravar"
version = "0.4.0"
description = "Subsetting a font file according to provided input."
readme = "README.md"
categories = ["text-processing"]
exclude = ["/test-data"]

edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/simoncozens/skeravar"
rust-version = "1.89"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bench]]
name = "skera-benchmarks"
harness = false

[[bin]]
name = "skeravar"
path = "src/main.rs"
required-features = ["cli"]

[features]
default = ["cli"]
cli = ["clap"]

[dependencies]
clap = { version = "4.5.4", features = ["derive"], optional = true }
env_logger = "0.11"

hashbrown = { version = "0.17.0", default-features = false, features = [
    "inline-more",
] }
log = "0.4.29"
num-traits = "0.2.18"
regex = "1.10.4"
thiserror = "2.0"
 # We need git version for composite flag setting. And because of that we need git versions of everything else too...
 # Everything is horrible, hope for a release soon.
write-fonts = { version = "0.51.0", features = ["read", "tables"] }
font-types =  { version = "0.12.1"}
skrifa =  { version = "0.45.0"}


[dev-dependencies]
criterion = "0.7.0"
diff = "0.1.13"
font-test-data = "0.7.0"
libtest-mimic = "0.8.1"
rstest = "0.26.1"
similar = "2.7.0"
tempfile = "3"

[[test]]
name = "integration_test"
harness = false
